bounswe/bounswe2024group10

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/repository/RegisteredUserRepository.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/RegistrationService.java
> Branch donomardanzakuduro

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/controller/RegisteredUserController.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/LoginRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/LoginResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/LoginService.java
Implement login messages and fix #102.
> Implement login messages and fix login issue.

- src/App.js
- src/pages/GuestSearch.js
- src/pages/GuestUserHome.js
I have added the pages related to the guest user. Please review @TheRealLowyer and give feedback to me.
> Guest user branch

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/controller/RegisteredUserController.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/RegisterRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/RegisterResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/model/RegisteredUser.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/LoginService.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/RegistrationService.java
Make the registration service follow the best programming practice.
> Add DTOs for registration service.

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/controller/LikeController.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/LikeRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/LikeResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/UnlikeRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/UnlikeResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/LikeService.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/UnlikeService.java
Title. Some issues regarding a like repository will be worked on soon.
> Controller, request, response, service implemented for the like feature.

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/controller/DislikeController.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/DislikeRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/DislikeResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/UndislikeRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/UndislikeResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/model/Disliked.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/repository/DislikedRepository.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/DislikeService.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/UndislikeService.java
Implemented controller, service, request, response and repository for dislike.
> Like dislike fix

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/model/Post.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/PostService.java
changed the post constructor to include username and changed other uses of the function accordingly.
> fix post username issue.

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/controller/SearchController.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/SearchResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/entity/AnimalInfoSearch.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/repository/PostRepository.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/SearchService.java
I have added more functionalities to the search such as getting the related posts for a searched animal, finding users and finding related animals when searcing an animal.
> Add AnimalInfoSearch

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/controller/PostController.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/GetUserPostInteractionsRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/GetUserPostInteractionsResponse.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/repository/BookmarkedRepository.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/PostService.java
Method: GET
Return Type:
boolean success;
String message;
boolean isLiked;
boolean isDisliked;
boolean isBookmarked;
> Add GetUserPostInteractions

- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/controller/PostController.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/dto/GetPostsRequest.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/model/Post.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/repository/PostRepository.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/PostService.java
- src/backend/animaltroove/src/main/java/com/bounswe2024group10/animaltroove/service/SearchService.java
I have added semantic properties to the posts, they now hold the family of the animal they have, which we can find in search
> Semantic post

- backend/pom.xml
- backend/src/main/java/com/bounswe2024group10/Tradeverse/config/SecurityConfig.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/UserController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/LoginRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/LoginResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/RegisterRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/RegisterResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/User.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/UserRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/UserService.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/util/JwtUtil.java
- backend/src/main/resources/application.properties
- docker-compose.yml
This pull request introduces an authentication mechanism for the Tradeverse application. It includes user registration and login functionalities, utilizing JWT (JSON Web Tokens) for secure session management. The following changes have been made to the codebase:
- Implemented the `register` method to handle user registration, including email and username validation.
- Implemented the `login` method to authenticate users and generate a JWT token upon successful login.
-   Added REST endpoints for user registration (`/api/auth/register`) and login (`/api/auth/login`).
- The controller returns appropriate responses based on the success or failure of the operations.
- Created a utility class for handling JWT operations, including token generation, validation, and extraction of user …
> Implement authentication

- mobile/tradeverse/app/(tabs)/create/index.jsx
This pull request fixes the mis-replacement of the Welcoming Screen in place of  the Create Screen
> hotfix: Fixed misreplacement of welcoming screen

- mobile/tradeverse/screens/add-asset/index.jsx
This pull request includes the implementation of the AddAssetScreen component that allows users to search for and add assets to their portfolio.
- The main screen component has been created to allow users to add assets to their portfolio by selecting an asset and entering an amount.
- Users can type in the asset's name, and the component filters and displays matching suggestions in real-time.
- When the user selects an asset from the suggestions, it populates the input field.
- Users are prompted to enter the amount of the selected asset in a numeric input field.
> Create Add Asset Screen

- mobile/tradeverse/screens/asset-detail/index.jsx
This pull request introduces the AssetDisplay component, which dynamically displays asset information, including the asset symbol, value in different currencies, and a graph image. The user can select a currency (USD, EUR, GBP) to see the value of the asset in that currency.
- Displays asset information for Bitcoin, including:
Symbol (BTC)
Asset name (Bitcoin)
Value in different currencies (USD, EUR, GBP)
Asset logo
- A picker component is included, allowing users to switch between currencies: USD, EUR, GBP.
- Asset value changes dynamically based on the selected currency, using hardcoded conversion rates for demonstration purposes.
- Asset value is converted from USD to the selected currency, and values are rounded to the nearest whole number.
> Create Asset Detail Screen

- mobile/tradeverse/app/(tabs)/account/profile.jsx
- mobile/tradeverse/components/inputs/RHFTextArea.jsx
- mobile/tradeverse/components/inputs/RHFTextField.jsx
- mobile/tradeverse/components/inputs/TextField.jsx
- mobile/tradeverse/components/inputs/TextField.style.js
- mobile/tradeverse/config/screen-paths.js
- mobile/tradeverse/mock/user-profile.js
- mobile/tradeverse/package-lock.json
- mobile/tradeverse/package.json
- mobile/tradeverse/screens/account-profile/index.jsx
- mobile/tradeverse/screens/account-root/_components/top-profile-info.jsx
- mobile/tradeverse/screens/welcoming/index.jsx
This pull request includes the creation of Profile Settings Screen.
- A component that can be used under the react hook form context.
- This is created to catch form values and errors easily through the application.
- Text Area version of the component above.
- **React Hook Form** for managing form states.
- **Zod** for creating validation schemas.
> feat: Create Profile Settings Screen

- mobile/tradeverse/app/(tabs)/create/index.jsx
- mobile/tradeverse/screens/profile/index.jsx
This pull request fixes the missing global screen component on Profile Screen. Also it fixes the text out of Text component error. The reason of the error is about writing comments with curly braces.
> Text out of Text component error, Missing Global Screen component

- mobile/tradeverse/screens/followed-tags/index.jsx
This pull request introduces the FollowedTagsScreen component, which displays a list of topics the user is following, along with the number of followers for each topic. It includes a header showing the number of followed topics, a list of tags, and a bottom navigation bar with buttons for Home, Search, Create, Notifications, and Profile.
- Displays the tags the user is following, with information about the number of followers.
- Each tag is shown in a styled box with shadow and border effects for a clean look.
- Includes five buttons: Home, Search, Create, Notifications, and Profile.
- The Create button is highlighted to indicate it as the active or primary action button.
- Uses Ionicons for icons in the navigation bar.
> Create Followed Tags Screen

- mobile/tradeverse/screens/create-post/index.jsx
This pull request introduces the Post Creation Screen. User can create post on this screen under selected sub forum topic.
- Created Screen with necessary input parameters.
- Simulated selection of sub topic forum under which post will be created.
- Post Title and Content
- Content area has attachments section at bottom.
> feat: Create Post Creation screen

- mobile/tradeverse/screens/followed-users/index.jsx
- mobile/tradeverse/screens/portfolio/index.jsx
This pull request introduces the FollowedUsersScreen component, which displays a list of followed users with profile information, including a profile picture, username, and follower count. The component leverages a scrollable and interactive list to allow users to view all followed profiles easily.
- Displays a list of followed users, including:
Profile image (placeholder image used in mock data)
Username
Number of followers
- Mock data simulates 14 followed users with randomly generated follower counts.
- Each user is presented in a block format that includes:
- A circular profile picture (Image)
- Username and follower count displayed next to the profile image
- The blocks are touchable (TouchableOpacity), allowing potential future functionality, such as navigating to a detailed profile …
> Followed Users Page Creation

- mobile/tradeverse/screens/subforum-detail/index.jsx
This pull request introduces the creation of the **Subforum Screen**, a UI component that displays posts related to stock marketing and investments. The screen includes interactive posts with features like viewing, liking, disliking, and commenting.
- A reusable component that displays post details such as profile picture, username, post title, view count, and interaction buttons (like, dislike, comments).
- Each post includes functionality to toggle like and dislike states, and dynamically updates the display of likes and dislikes.
- A main screen for displaying posts in a vertical scrollable view using `ScrollView`. 
- Posts are rendered using mock data and displayed in a clean, styled format with a light purple theme.
- `GlobalScreen` and `FullScrollView` components are used to ensure …
> feat: Create Subforum Detail Screen

- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/RegisterResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/UserService.java
This pull request updates the user registration functionality in the Tradeverse application to return a JWT token and the username upon successful registration.
This enhancement improves the user experience by providing immediate authentication details upon registration, facilitating smoother integration with client applications.
> Respond with token and username on register

- backend/src/main/java/com/bounswe2024group10/Tradeverse/config/SecurityConfig.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/UserController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/GetUserDetailsRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/GetUserDetailsResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/User.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/UserService.java
This pull request introduces the bio field to the User model, enhancing user profiles by allowing them to include a personal description.
The GetUserDetailsResponse DTO has been updated to include the bio information, and the UserService has been modified to return this new field when fetching user details. 
This enhancement aims to improve user engagement and personalization within the application.
> Implement get-user-details endpoint

- mobile/tradeverse/app/(tabs)/_layout.jsx
- mobile/tradeverse/app/(tabs)/home/index.jsx
- mobile/tradeverse/app/_layout.jsx
- mobile/tradeverse/app/auth.jsx
- mobile/tradeverse/auth/context/auth-context.jsx
- mobile/tradeverse/auth/context/auth-guard.jsx
- mobile/tradeverse/auth/context/auth-provider.jsx
- mobile/tradeverse/auth/context/index.jsx
- mobile/tradeverse/auth/screens/login/index.jsx
- mobile/tradeverse/auth/ui/AuthLoader.js
- mobile/tradeverse/package-lock.json
- mobile/tradeverse/package.json
- mobile/tradeverse/screens/account-profile/index.jsx
- mobile/tradeverse/screens/account-root/_components/top-profile-info.jsx
- mobile/tradeverse/screens/account-root/index.jsx
- mobile/tradeverse/screens/create-post/index.jsx
- mobile/tradeverse/screens/create-subforum/index.jsx
- mobile/tradeverse/screens/home-root/index.jsx
- mobile/tradeverse/screens/profile/index.jsx
- mobile/tradeverse/services/_axios.js
- mobile/tradeverse/services/auth.js
- mobile/tradeverse/services/user.js
- mobile/tradeverse/tsconfig.json
This pull request introduces authentication features and integrates real backend services for user sign-in and registration. Additionally, existing screens and components were updated to handle authentication and display user information.
- **Auth Context & Auth Provider**
- Created `AuthContext` and `AuthProvider` to manage and share authentication state throughout the app.
- **AuthLoader Screen**
- Added a new `AuthLoader` screen to display while authentication checks are running.
- **AuthGuard Component**
- Implemented `AuthGuard` to protect routes and redirect unauthenticated users to the login screen when authentication fails.
- **Authentication Services**
- Created `signIn` and `register` services to handle user sign-in and registration by sending real-time HTTP requests to the …
> feat: Mobile Authentication applied.

- mobile/tradeverse/screens/explore-root/_components/post-card.jsx
- mobile/tradeverse/screens/explore-search-results/_components/result-cards/user-result.jsx
- mobile/tradeverse/screens/post-detail/_components/post-header.jsx
This pull request fixes a small bug in user links.
- Some user links were directing to the empty page since they lacked the user object property they need to be able to navigate to the correct user page.
> fix: Fix the false navigation in some user links.

- backend/src/main/java/com/bounswe2024group10/Tradeverse/config/SecurityConfig.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/FollowController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/FollowUserRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/FollowUserResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/GetFollowersRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/GetFollowersResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/GetFollowingsRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/GetFollowingsResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/UnfollowUserRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/follow/UnfollowUserResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/Follow.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/FollowRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/FollowService.java
This pull request implements the follow mechanism in the application, allowing users to follow and unfollow each other, as well as retrieve their followers and followings. The functionality is encapsulated in a new service and controller, with appropriate request and response DTOs.
> Implement follow

- mobile/tradeverse/eas.json
This pull request includes the addition of the eas.js file for the apk build.
- **eas.js**
- eas.js file with proper configurations has been added to be able to generate apk of the application.
> env: Upload eas.js file

- mobile/tradeverse/app.json
- mobile/tradeverse/auth/context/auth-provider.jsx
- mobile/tradeverse/components/ui/global-screen.jsx
- mobile/tradeverse/mock-data/all-tags.js
- mobile/tradeverse/mock-services/assets.js
- mobile/tradeverse/screens/explore-search-results/index.jsx
- mobile/tradeverse/screens/portfolio/index.jsx
- mobile/tradeverse/screens/post-detail/index.jsx
This pull request includes refactor process of the some screen ui's and the authentication logic which is created spesifically for the Milestone demo 1.
- **Portfolio Screen**
- My Portfolio screen has been changed so that portfolio asset boxes have now different stylings.
- **GlobalScreen Change**
- Since SafeAreaView component is only valid for ios, a default padding has been added based on the device OS.
- **Tags**
- Added two new tags into the all-tags.js file.
- 
- Removed unnecessary lines for navigating the user after selection of the tags.
> refactor: Refactor Auth Logic and UI

- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/Portfolio.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/PortfolioRepository.java
* portfolio table (model) is created, columns: username, name, visibility (public or private), createdAt (date of creation).
> create portfolio table and repository class

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/PortfolioController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/portfolio/CreatePortfolioRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/portfolio/CreatePortfolioResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/portfolio/GetAllPortfoliosRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/portfolio/GetAllPortfoliosResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/portfolio/PortfolioDto.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/portfolio/UpdatePortfolioRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/portfolio/UpdatePortfolioResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/Portfolio.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/PortfolioRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PortfolioService.java
* This PR is same as the [390](https://github.com/bounswe/bounswe2024group10/pull/390)
> Implement portfolio endpoint

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/FollowSubforumController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/PostController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GeneralFollowSubforumRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GeneralFollowSubforumResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GetFollowingsRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GetFollowingsResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/post/FeedRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/post/FeedResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/extra/SubforumWSpecs.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/FollowSubforum.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/FollowSubforumRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/FollowSubforumService.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PostService.java
Added the feed endpoint, it currently does not have the "for-you" part but it will be implemented soon.
> Feed endpoint

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/FollowSubforumController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GeneralFollowSubforumRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GeneralFollowSubforumResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GetFollowingsRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/followSubforum/GetFollowingsResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/extra/SubforumWSpecs.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/FollowSubforum.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/FollowSubforumRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/FollowSubforumService.java
Added follow sub-forum functionality and its endpoints.
> Follow subforum

- web/tradeverse/package-lock.json
- web/tradeverse/package.json
- web/tradeverse/src/components/structure/RenderNavigation.js
- web/tradeverse/src/components/styles/style.module.css
- web/tradeverse/src/pages/Account.js
- web/tradeverse/src/pages/styles/Account.css
- Design account page. (Account.js and account.css)
- Add access from right-menu on the home page.
- Add access from sidebar on the home page.
- Delete the portfolio section from account page. (A separate portfolio page will exist for this purpose)
- Add editing functionalities to account page.
- Use mock data by manual data insertion into HTML.
> Web - Create account page, its view, and its access points.

- web/tradeverse/src/pages/Search.js
- web/tradeverse/src/pages/styles/Search.module.css
> popular fix

- web/tradeverse/src/components/structure/subforumNavbar.js
- web/tradeverse/src/components/styles/subforumNavbar.module.css
Adjust navbar so that the selected section has a slightly different colour background.
> Navbar selection shadow

- web/tradeverse/src/components/structure/RenderNavigation.js
- web/tradeverse/src/components/structure/subforumNavbar.js
> header-subforums added

- web/tradeverse/package-lock.json
- web/tradeverse/package.json
- web/tradeverse/src/__test__/Signup.test.jsx
- web/tradeverse/src/pages/Home.js
This PR introduces the Jest testing framework to the project and adds the first set of unit tests for the Signup component. The following changes have been made:
Jest Setup:
Installed necessary Jest testing dependencies (jest, @testing-library/react, @testing-library/user-event, etc.) and updated the package.json to include them.
Signup Component Tests:
Created a new test file: Signup.test.jsx.
Added tests to verify the behavior of the Signup component, including:
Rendering the component and checking for initial elements.
Validating error messages when fields are left empty.
Navigating between steps in the Signup form on valid input.
Handling invalid user type selection.
Simulating a successful registration process.
Key Tests Implemented:
Renders Signup Component: Verifies that the Signup …
> Web unit test

- web/tradeverse/src/components/structure/subforumNavbar.js
This pull request adds shadowing to the navbar. The currently active selection on the navbar is slightly highlighted, letting the user know which option is active.
> Lab 8 - Navbar

- backend/src/test/java/service/PortfolioServiceUnitTest.java
Test add asset to portfolio, false if assets is not in assets repository. @gulsensabak and @NazlicanAka done this pull request.
> Test add asset to portfolio

- backend/src/test/java/service/PortfolioServiceUnitTest.java
correct the wrong logic about unit test. With @gulsensabak
> hot fix unit test

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/AssetController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/User.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/AssetService.java
- web/tradeverse/src/components/structure/RenderNavigation.js
- web/tradeverse/src/pages/AssetInfo.js
---
This pull request introduces a dynamic `AssetInfo` page in the application, which fetches and displays asset details based on the asset ID passed through the route parameters. The page integrates with the backend API to retrieve real-time data and renders the information in a structured layout.
---
1. **Dynamic Asset Fetching:**
- Integrated the backend API (`GET /api/asset/{id}`) to fetch asset details dynamically based on the route parameter `id`.
- Utilized React's `useEffect` and `fetch` API to perform the data retrieval.
- Implemented proper loading and error states to handle API calls gracefully.
2. **AssetInfo Component:**
- Updated the `AssetInfo` component to:
- Extract the `id` parameter from the URL using React Router's `useParams`.
- Fetch asset details and render them …
> Dynamic Asset info page for different assets

- mobile/tradeverse/auth/context/auth-provider.jsx
- mobile/tradeverse/components/links/subforum-link.jsx
- mobile/tradeverse/package-lock.json
- mobile/tradeverse/screens/add-asset/_components/AssetSuggestion.jsx
- mobile/tradeverse/screens/create-post/_components/SubforumSuggestion.jsx
- mobile/tradeverse/screens/explore-root/_components/subforum-card.jsx
- mobile/tradeverse/screens/explore-root/_components/tabs.jsx
- mobile/tradeverse/screens/explore-root/index.jsx
- mobile/tradeverse/screens/explore-root/views/recent-view.jsx
- mobile/tradeverse/screens/explore-root/views/subforums-view.jsx
- mobile/tradeverse/screens/explore-search-results/index.jsx
- mobile/tradeverse/screens/subforum-detail/_components/post-card.jsx
- mobile/tradeverse/screens/subforum-detail/index.jsx
- mobile/tradeverse/services/_axios.js
- mobile/tradeverse/services/subforum.js
- mobile/tradeverse/util/format-date.js
This PR introduces the following improvements and new features for subforums:
1. **Explore Page Enhancements**:
- Subforums are now displayed by default on the explore page, providing users with easier access to browse and discover subforums.
2. **Subforum Detail Page Improvements**:
- The detail page of a subforum now displays additional information:
- **Number of Posts**: View the total posts available in the subforum.
- **Number of Followers**: See how many users are following the subforum.
3. **Follow/Unfollow Functionality**:
- Users can now follow or unfollow subforums directly from the UI.
4. **Loading Skeletons**:
- When subforum data is not yet loaded, a loading skeleton is displayed. This skeleton is designed to match the real UI, providing a smooth and consistent user …
> Subforum Explore and Detail

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/PortfolioController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PortfolioService.java
* Changed the end-point "get-portfolio" to take @RequestBody
* Changed the end-point "by-asset" to take @PathVariable
* [issue](https://github.com/bounswe/bounswe2024group10/issues/460)
> Fix get-portfolio and by-asset endpoints

- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/Post.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/PostRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PostService.java
* Keep the view count for the posts. Every time "get post" is done view count should be increased by one.
* See the related [issue](https://github.com/bounswe/bounswe2024group10/issues/490)
> View count enhancement for posts

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/AssetController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/asset/AddAssetRequest.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/asset/AddAssetResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/model/Asset.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/AssetService.java
Added the **nullable** imageUrl field to Asset object. Modified the asset retrieving Python script to get image urls for each object.
> Add imageUrl to assets.

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/ImageController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/AuthenticationService.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PostService.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/UserService.java
- web/tradeverse/src/components/structure/RenderNavigation.js
- web/tradeverse/src/components/structure/feed.js
- web/tradeverse/src/services/api.js
* Change baseURL of mobile repo to local.
* Change images directory from images to /images in backend container.
* Add imageController to serve images.
You can access the files using `http://<hostname>/api/images/image_file.jpg`
> Add ImageController to serve images.

- mobile/tradeverse/app/(tabs)/account/followers.jsx
- mobile/tradeverse/config/screen-paths.js
- mobile/tradeverse/screens/account-root/profile-config.js
- mobile/tradeverse/screens/followers/index.jsx
Followers screen enabled & implemented in the navigation stack. Real data fetching and displaying in the screen.
> imp: Followers screen

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/PostController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/PostRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PostService.java
Implemented /api/post/get-posts-by-tag endpoint
(Tested it)
> Get posts by tag endpoint

- backend/src/main/java/com/bounswe2024group10/Tradeverse/controller/PostController.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PostService.java
> Endpoint which returns posts created by an user

- web/tradeverse/src/components/structure/Post.js
- web/tradeverse/src/components/structure/RenderNavigation.js
- web/tradeverse/src/components/structure/comment.js
- web/tradeverse/src/components/structure/navigation.js
- web/tradeverse/src/components/structure/postHeader.js
- web/tradeverse/src/components/styles/post.module.css
- web/tradeverse/src/components/styles/postHeader.module.css
- web/tradeverse/src/pages/Portfolio.js
- web/tradeverse/src/pages/PostPage.js
- web/tradeverse/src/pages/Search.js
- web/tradeverse/src/pages/Subforum.js
- web/tradeverse/src/pages/TagPage.js
- web/tradeverse/src/pages/styles/TagPage.module.css
- web/tradeverse/src/services/post.js
This PR introduces the **TagPage** component, enabling users to explore posts associated with specific tags. It includes updates to routing, links, and enhancements to the user experience.
---
1. **TagPage Component**:
- Created a `TagPage` component that:
- Fetches posts associated with a specific tag from the backend.
- Displays the posts using the existing `Feed` component.
- Includes a header displaying the tag name with styled elements.
- Handles loading and error states gracefully.
2. **Service Integration**:
- Implemented the `getPostsByTag` service function to fetch posts from the backend using the endpoint:
```
GET /api/post/get-posts-by-tag?tag=@TAG
```
- Passes the `Authorization` token for authenticated users.
- Handles unauthenticated requests by passing an empty string as …
> Add TagPage Functionality with Routing and Links

- web/tradeverse/src/pages/Account.js
- web/tradeverse/src/pages/styles/Account.css
- web/tradeverse/src/pages/styles/User.css
The account page was unaccessible due to a content error. The content type of our actual posts and the posts within the account page differed and this caused a type error. I fixed this by changing the material inside the post content of the account page to fit the correct post structure. 
I also added a "Go To My Portfolio" button on the bottom of the account page. This button simply links to the users own portfolio page. 
Edit: Reduced the width of bio and post sections.
> Account page error

- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/PostService.java
- backend/src/test/java/service/PostServiceUnitTest.java
Currently main passes all tests
> Post service unit tests

- backend/src/main/java/com/bounswe2024group10/Tradeverse/dto/post/GetPostResponse.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/repository/PostRepository.java
- backend/src/main/java/com/bounswe2024group10/Tradeverse/service/UserService.java
> Fix for /api/user/profile
